import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"


[font]
normal = {family = "FiraCode Nerd Font"}
size = 11.0

# [window]
# decorations = "None"

