import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "zsh"
args = ["-l", "-c", "tmux"]

[font]
normal = {family = "FiraCode Nerd Font"}
size = 12.0

[window]
decorations = "None"

